version: '{build}'
os: Windows Server 2012

cache:
- C:\maven\ -> appveyor.yml
- C:\Users\appveyor\.m2\ -> pom.xml

environment:
  MAVEN_VERSION: 3.6.0
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master
  - glcd-release-.*

install:
- ps: |
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    if (!(Test-Path -Path "C:\maven" )) {
      Write-Host "Downloading Maven $env:MAVEN_VERSION"
      (new-object System.Net.WebClient).DownloadFile("https://repo1.maven.org/maven2/org/apache/maven/apache-maven/$env:MAVEN_VERSION/apache-maven-$env:MAVEN_VERSION-bin.zip", 'C:\maven-bin.zip')
      [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
    }
- cmd: SET M2_HOME=C:\maven\apache-maven-%MAVEN_VERSION%
- cmd: SET PATH=%M2_HOME%\bin;%JAVA_HOME%\bin;%PATH%
- cmd: mvn --version
- cmd: java -version

artifacts:
- path: 'target\jfx\native\glcd-emulator-*.exe'
- path: 'target\glcd-emulator-*-nojre.zip'
- path: 'target\glcd-emulator-*-nojre.tar.gz'

build_script:
- mvn -B clean package
- mvn -B test && mvn verify

matrix:
  fast_finish: true

deploy:
  provider: GitHub
  auth_token:
    secure: "HoEC1gCy7yKVD9Bp4AOuql+DH7nzFSMOJhdQQQ2O+GOdSqljp2jxWDsMQtREYOoz"
  artifact: target/glcd-emulator-.*-nojre\.tar\.gz, target/glcd-emulator-.*-nojre\.zip, target/jfx/native/glcd-emulator-.*\.exe
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true